#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "hybrid"
  background = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  termguicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_display_mode = false
  filemanager = "nerdtree"
  sidebar_direction = 'left'
  relativenumber = true
  bootstrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"

[[custom_plugins]]
  name = "hashivim/vim-terraform"
  merged = false

[[custom_plugins]]
  name = "mhartington/oceanic-next"
  merged = false

[[custom_plugins]]
  name = "ayu-theme/ayu-vim"
  merged = false

[[custom_plugins]]
  name = "tpope/vim-fugitive"
  merged = false

[[custom_plugins]]
  name = "mhinz/vim-signify"
  merged = false

[[custom_plugins]]
  name = "akoutmos/vim-devicons"
  # name = "ryanoasis/vim-devicons"
  merged = false

[[custom_plugins]]
  name = "reisub0/hot-reload.vim"
  merged = false

[[layers]]
  name = "colorscheme"

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "git"

[[layers]]
  name = "fzf"

[[layers]]
  name = "checkers"

[[layers]]
  name = "format"

[[layers]]
  name = "lang#elixir"

[[layers]]
  name = "lang#erlang"

[[layers]]
  name = "lang#elm"

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#javascript"
  enable_flow_syntax = true

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#haskell"

[[layers]]
  name = "lang#julia"

[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#php"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "lang#tests"

[[layers]]
  name = "lang#typescript"
  
[[layers]]
  name = "lang#dart"

[[layers]]
  name = "lang#swift"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#autohotkey"

[[layers]]
  name = "ui"

